import { ADDITIONAL_LICENCES, BASE_LICENCES, PREMIUM_OF } from '../types';
import type {
  BaseLicence,
  CustomProcess,
  LicenceRequirement,
  Profile,
  ProfilingMode,
  Project,
} from '../types';
import { catalogLicence } from '../data/catalog';
import { getStandardRole } from '../data/standardRoles';

export type BaseFlags = Record<BaseLicence, 0 | 1>;

export interface ProfileResult {
  profileId: string;
  totalUsers: number;
  /** Row 158:163 of the workbook — one flag per base licence family. */
  baseFlags: BaseFlags;
  /** Row 165 — number of users requiring a base (full) licence. */
  base: number;
  /** Row 166 — number of attach licences generated by additional base families. */
  addOn: number;
  /** Rows 167/168/169 — additional licence types, mutually exclusive with base. */
  activity: number;
  teamMembers: number;
  device: number;
  /** Rows 171:176 — base licence allocated per product. */
  baseByProduct: Record<BaseLicence, number>;
  /** Rows 177:182 — attach licence allocated per product. */
  attachByProduct: Record<BaseLicence, number>;
}

export interface LicenceTotals {
  base: Record<BaseLicence, number>;
  attach: Record<BaseLicence, number>;
  activity: number;
  teamMembers: number;
  device: number;
  totalBase: number;
  totalAddOn: number;
}

export interface ProjectResult {
  profiles: ProfileResult[];
  totals: LicenceTotals;
  /** legalEntityId -> totals restricted to that legal entity's user counts. */
  byLegalEntity: Record<string, LicenceTotals>;
}

function zeroBase(): Record<BaseLicence, number> {
  return BASE_LICENCES.reduce((acc, key) => {
    acc[key] = 0;
    return acc;
  }, {} as Record<BaseLicence, number>);
}

function emptyTotals(): LicenceTotals {
  return {
    base: zeroBase(),
    attach: zeroBase(),
    activity: 0,
    teamMembers: 0,
    device: 0,
    totalBase: 0,
    totalAddOn: 0,
  };
}

/**
 * Resolves the licence requirement of a process id, looking first in the
 * standard catalog then in the project's custom processes.
 */
export function resolveLicence(processId: string, customProcesses: CustomProcess[]): LicenceRequirement {
  const fromCatalog = catalogLicence(processId);
  if (fromCatalog !== undefined) return fromCatalog;
  return customProcesses.find((p) => p.id === processId)?.licence ?? null;
}

/**
 * Licence requirements triggered by a profile, reading only the input of the
 * active profiling mode. The other mode's data is left untouched so the user can
 * switch back without losing anything.
 */
export function selectedLicences(
  profile: Profile,
  customProcesses: CustomProcess[],
  mode: ProfilingMode,
): Set<string> {
  const result = new Set<string>();
  if (mode === 'processes') {
    for (const [processId, selected] of Object.entries(profile.selections)) {
      if (!selected) continue;
      const licence = resolveLicence(processId, customProcesses);
      if (licence) result.add(licence);
    }
  } else {
    for (const [roleId, selected] of Object.entries(profile.standardRoles ?? {})) {
      if (!selected) continue;
      const licence = getStandardRole(roleId)?.licence;
      if (licence) result.add(licence);
    }
  }
  return result;
}

export function totalUsers(profile: Profile): number {
  return Object.values(profile.counts).reduce((sum, n) => sum + (Number.isFinite(n) ? n : 0), 0);
}

/**
 * Core licence computation for one profile, mirroring rows 158-182 of the
 * reference workbook. `users` is injected so the same rules can be replayed on a
 * per-legal-entity subset without changing the licence decisions.
 */
export function computeProfile(
  profile: Profile,
  customProcesses: CustomProcess[],
  users: number,
  mode: ProfilingMode,
): ProfileResult {
  const licences = selectedLicences(profile, customProcesses, mode);

  const baseFlags = BASE_LICENCES.reduce((acc, key) => {
    acc[key] = licences.has(key) ? 1 : 0;
    return acc;
  }, {} as BaseFlags);

  // A Premium edition is a superset of its standard sibling, so it absorbs it
  // instead of generating a second licence for the same product family.
  for (const [premium, standard] of Object.entries(PREMIUM_OF) as [BaseLicence, BaseLicence][]) {
    if (baseFlags[premium]) baseFlags[standard] = 0;
  }

  const requiredFamilies = BASE_LICENCES.filter((key) => baseFlags[key] === 1);
  const baseFamilyCount = requiredFamilies.length;

  const base = users * (baseFamilyCount > 0 ? 1 : 0);
  const addOn = users * (baseFamilyCount > 0 ? baseFamilyCount - 1 : 0);

  const activity = users * (base === 0 && licences.has('activity') ? 1 : 0);
  const teamMembers = users * (base === 0 && activity === 0 && licences.has('teamMembers') ? 1 : 0);
  const device = users * (base === 0 && licences.has('device') ? 1 : 0);

  // BASE_LICENCES is ordered by price, so the first required family carries the
  // base licence and every other required family becomes an attach licence.
  const baseByProduct = zeroBase();
  const attachByProduct = zeroBase();
  requiredFamilies.forEach((key, index) => {
    if (index === 0) baseByProduct[key] = base;
    else attachByProduct[key] = users;
  });

  return {
    profileId: profile.id,
    totalUsers: users,
    baseFlags,
    base,
    addOn,
    activity,
    teamMembers,
    device,
    baseByProduct,
    attachByProduct,
  };
}

function accumulate(totals: LicenceTotals, result: ProfileResult): void {
  for (const key of BASE_LICENCES) {
    totals.base[key] += result.baseByProduct[key];
    totals.attach[key] += result.attachByProduct[key];
  }
  totals.activity += result.activity;
  totals.teamMembers += result.teamMembers;
  totals.device += result.device;
  totals.totalBase += result.base;
  totals.totalAddOn += result.addOn;
}

export function computeProject(project: Project): ProjectResult {
  const totals = emptyTotals();
  const byLegalEntity: Record<string, LicenceTotals> = {};
  for (const entity of project.legalEntities) {
    byLegalEntity[entity.id] = emptyTotals();
  }

  const mode = project.profilingMode;
  const profiles = project.profiles.map((profile) => {
    const result = computeProfile(profile, project.customProcesses, totalUsers(profile), mode);
    accumulate(totals, result);

    for (const entity of project.legalEntities) {
      const users = profile.counts[entity.id] ?? 0;
      if (users <= 0) continue;
      accumulate(byLegalEntity[entity.id], computeProfile(profile, project.customProcesses, users, mode));
    }

    return result;
  });

  return { profiles, totals, byLegalEntity };
}

export const ALL_LICENCE_KEYS = [...BASE_LICENCES, ...ADDITIONAL_LICENCES];
